config/routes.rb
Rails.application.routes.draw do
  root 'books#index'
  devise_for :users

  resources :books, only: [:index, :show, :new, :create]
  resources :reviews, only: [:create, :new]

  namespace :api do
    namespace :v1 do
      resources :books, only: [:show, :new, :index, :create]
      resources :reviews, only:[:new, :create, :show]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates_presence_of :name, :author, :isbn, :description, :publication_date
  validates_uniqueness_of :isbn, case_sensitive: false
  validates_numericality_of :isbn
  validates_length_of :isbn, minimum: 10, maximum: 13
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  validates_presence_of :rating, :likes, :dislikes, :book_id, :user_id
  validates_inclusion_of :rating, :in => 1..5
  validates_numericality_of :likes, greater_than_or_equal_to: 0
  validates_numericality_of :dislikes, greater_than_or_equal_to: 0
  belongs_to :book
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :avatar, AvatarUploader
  validates_presence_of :email, :encrypted_password, :first_name, :last_name
  validates_length_of :encrypted_password, minimum: 6

  has_many :reviews

  if :avatar
    validates_integrity_of  :avatar
    validates_processing_of :avatar
  end

  def admin?
    role == "admin"
  end
end

app/controllers/api/v1/books_controller.rb
class Api::V1::BooksController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }

  def show
    book = Book.find(params[:id])
    render json: book
  end
end

app/controllers/api/v1/reviews_controller.rb
class Api::V1::ReviewsController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :authorize_user, except: [:show, :index]

  def create
    review = Review.create(review_params)
    review.user = current_user
      if review.save
        render json: review
      else
        render json: {error: review.errors.full_messages}, status: :unprocessable_entity
      end
  end

  def show
    review = Review.find(params[:id])
    render json: review
  end

  private

  def review_params
    params.require(:review).permit(:rating, :comment, :book_id, :likes, :dislikes, :user_id)
  end

  def authorize_user
    if !current_user
      render json: {error: "Please sign up or sign in to access this feature."}, status: :unprocessable_entity
    end
  end

  def current_user_access
    current_user.id == Review.find(params[:id]).user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :first_name, :last_name, :avatar, :avatar_cache, :remove_avatar) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :first_name, :last_name, :avatar, :avatar_cache, :remove_avatar, :current_password) }
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authorize_user, except: [:show, :index]

  def index
    @books = Book.paginate(page: params[:page], per_page: 10)
  end

  def show

  end

  def new
    if current_user
      @book = Book.new
      render :new
    else
      @books = Book.paginate(page: params[:page], per_page: 10)
      render :index
    end
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      flash[:notice] = "Book added successfully!"
      redirect_to @book
    else
      flash[:error] = @book.errors.full_messages.join(". \n")
      render :new
    end
  end

  private

  def book_params
    params.require(:book).permit(:name, :author, :publication_date, :description, :isbn)
  end

  def authorize_user
    if !current_user
      flash[:notice] = "You must be signed in to add a book!"
    end
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

end

app/views/books/index.html.erb
<h2 class="heading"> All Books </h2>

<div class="next-page">
  <%= will_paginate %>
</div>
<br>
<ul class="flex-container">
  <% @books.each do |book| %>
  <li class="book_box"><%= link_to book.name, book_path(book)%></li>
  <br>
  <% end %>
</ul>
<div class="new-book">
<%= link_to "Add New Book", new_book_path %>
</div>

app/views/books/new.html.erb
<h2 class="new-book">New Book Form</h2>
<div class="form">
<%= form_for @book do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.label :isbn %>
  <%= f.text_field :isbn %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :publication_date %>
  <%= f.text_field :publication_date %>

  <%= f.submit "Add Book" %>

<% end %>
</div>

app/views/books/show.html.erb
  <div id="app"></div>

app/views/homes/index.html.erb
<p>
  Modify me in `app/views/homes/index.html.erb` or change the root directive in
  `config/routes.rb`
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BookReviews</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= javascript_include_tag "vendor/modernizr" %>

  <%= csrf_meta_tags %>
</head>
<body>

  <nav class="top-bar">
    <ul class="title-area">
      <li class="name">
        <h1><a href="/">BookReviews</a></h1>
      </li>
    </ul>

    <section class="top-bar-section">
      <ul class="right">
        <%- if current_user -%>
          <li><a><%="Welcome, #{current_user.first_name}!"%></a></li>
          <% if current_user.avatar.url%>
            <li><img src="<%=current_user.avatar.url%>" class="img-responsive"></li>
          <% end %>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Sign In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
</body>
</html>